version: '3'

services:
  api:
    image: api
    build:
      context: ./API
      dockerfile: Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile
